In [3]:
import urllib, requests, json
import pandas as pd
import json
from pprint import pprint
from pandas import DataFrame

In [4]:
# stnIds(종관기상관측 번호) 데이터 가져오기
stn = pd.read_csv("./stnInfo.csv", encoding='euc-kr')
stn

,지점,시작일,종료일,지점명,관리관서,위도,경도,노장해발고도(m),기압계(관측장비지상높이(m)),기온계(관측장비지상높이(m)),풍속계(관측장비지상높이(m)),강우계(관측장비지상높이(m))
0,3,1900-01-01,NaN,선봉,NaN,42.3167,130.4000,3.00,NaN,NaN,NaN,NaN
1,5,1900-01-01,NaN,삼지연,NaN,41.8167,128.3167,1386.00,NaN,NaN,NaN,NaN
2,8,1900-01-01,NaN,청진,NaN,41.7833,129.8167,43.00,NaN,NaN,NaN,NaN
3,14,1900-01-01,NaN,중강,NaN,41.7833,126.8833,332.00,NaN,NaN,NaN,NaN
4,16,1900-01-01,NaN,혜산,NaN,41.4000,128.1667,714.00,NaN,NaN,NaN,NaN
5,20,1900-01-01,NaN,강계,NaN,40.9667,126.6000,306.00,NaN,NaN,NaN,NaN
6,22,1900-01-01,NaN,풍산,NaN,40.8167,128.1500,1206.00,NaN,NaN,NaN,NaN
7,25,1900-01-01,NaN,김책,NaN,40.6667,129.2000,23.00,NaN,NaN,NaN,NaN
8,28,1900-01-01,NaN,수풍,NaN,40.4500,124.9333,83.00,NaN,NaN,NaN,NaN
9,31,1900-01-01,NaN,장진,NaN,40.3667,127.2500,1081.00,NaN,NaN,NaN,NaN
10,35,1900-01-01,NaN,신의주,NaN,40.1000,124.3833,7.00,NaN,NaN,NaN,NaN
11,37,1900-01-01,NaN,구성,NaN,39.9833,125.2500,99.00,NaN,NaN,NaN,NaN
12,39,1900-01-01,NaN,희천,NaN,40.1667,126.2500,155.00,NaN,NaN,NaN,NaN
13,41,1900-01-01,NaN,함흥,NaN,39.9333,127.5500,38.00,NaN,NaN,NaN,NaN
14,46,1900-01-01,NaN,신포,NaN,40.0333,128.1833,19.00,NaN,NaN,NaN,NaN
15,50,1900-01-01,NaN,안주,NaN,39.6167,125.6500,27.00,NaN,NaN,NaN,NaN
16,52,1900-01-01,NaN,양덕,NaN,39.1667,126.8333,279.00,NaN,NaN,NaN,NaN
17,55,1900-01-01,NaN,원산,NaN,39.1833,127.4333,36.00,NaN,NaN,NaN,NaN
18,58,1900-01-01,NaN,평양,NaN,39.0333,125.7833,38.00,NaN,NaN,NaN,NaN
19,60,1900-01-01,NaN,남포,NaN,38.7167,125.3667,47.00,NaN,NaN,NaN,NaN
20,61,1900-01-01,NaN,장전,NaN,38.7333,128.1833,35.00,NaN,NaN,NaN,NaN
21,65,1900-01-01,NaN,사리원,NaN,38.5167,125.7667,52.00,NaN,NaN,NaN,NaN
22,67,1900-01-01,NaN,신계,NaN,38.5000,126.5333,100.00,NaN,NaN,NaN,NaN
23,68,1900-01-01,NaN,용연,NaN,38.2000,124.8833,5.00,NaN,NaN,NaN,NaN
24,69,1900-01-01,NaN,해주,NaN,38.0333,125.7000,81.00,NaN,NaN,NaN,NaN
25,70,1900-01-01,NaN,개성,NaN,37.9667,126.5667,70.00,NaN,NaN,NaN,NaN
26,75,1900-01-01,NaN,평강,NaN,38.4000,127.3000,371.00,NaN,NaN,NaN,NaN
27,90,1968-01-01,NaN,속초,속초기상대(90),38.2509,128.5647,17.53,18.73,1.7,10.0,1.4
28,90,2006-12-08,NaN,속초,강릉(구 105),38.2509,128.5647,18.06,NaN,NaN,NaN,NaN
29,92,2002-02-25,NaN,양양공항,NaN,38.0667,128.6667,75.40,72.00,1.5,10.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...
4611,78224,2002-04-15,NaN,하바나,NaN,22.9833,-82.4000,NaN,NaN,NaN,NaN,NaN
4612,78322,2002-04-15,NaN,BATABANO,NaN,22.7167,-82.2833,NaN,NaN,NaN,NaN,NaN
4613,78439,2002-04-15,NaN,PORT-AU-PRINCE/AEROPORT INT.,NaN,18.5667,-72.3000,31.00,NaN,NaN,NaN,NaN
4614,78486,2002-04-15,NaN,산토도밍고,NaN,18.4333,-69.8833,NaN,NaN,NaN,NaN,NaN
4615,78526,2002-04-15,NaN,상환,NaN,18.4167,-65.9833,4.00,NaN,NaN,NaN,NaN
4616,78741,2002-04-15,NaN,마나과,NaN,12.1500,-86.1667,NaN,NaN,NaN,NaN,NaN
4617,80022,2002-04-15,NaN,카르타헤나,NaN,10.4500,-75.5167,1.00,NaN,NaN,NaN,NaN
4618,80222,2002-04-15,NaN,보고타,NaN,4.7000,-74.1500,2547.00,NaN,NaN,NaN,NaN
4619,80415,2002-04-15,NaN,카라카스,NaN,10.6000,-66.9833,43.00,NaN,NaN,NaN,NaN
4620,80419,2002-04-15,NaN,BARCELONA,NaN,10.1167,-64.6833,7.00,NaN,NaN,NaN,NaN
4621,83378,2002-04-15,NaN,브라질리아,NaN,-15.8667,-47.9333,1061.00,NaN,NaN,NaN,NaN
4622,83743,2002-04-15,NaN,리우데쟈네이로,NaN,-22.9167,-43.1667,5.00,NaN,NaN,NaN,NaN
4623,83780,2002-04-15,NaN,상파울로,NaN,-23.6167,-46.6500,803.00,NaN,NaN,NaN,NaN
4624,83840,2002-04-15,NaN,CURITIBA (AEROPORTO),NaN,-25.5167,-49.1667,908.00,NaN,NaN,NaN,NaN
4625,84071,2002-04-15,NaN,키토,NaN,-0.1333,-78.4667,NaN,NaN,NaN,NaN,NaN
4626,84628,2002-04-15,NaN,리마,NaN,-12.0000,-77.1167,12.00,NaN,NaN,NaN,NaN
4627,85201,2002-04-15,NaN,라파즈,NaN,-16.5167,-68.1833,4058.00,NaN,NaN,NaN,NaN
4628,85574,2002-04-15,NaN,푸다후엘,NaN,-33.3833,-70.7833,474.00,NaN,NaN,NaN,NaN
4629,86218,2002-04-15,NaN,아순션,NaN,-25.2667,-57.6333,NaN,NaN,NaN,NaN,NaN
4630,86580,2002-04-15,NaN,카라스코,NaN,-34.8333,-56.0000,32.00,NaN,NaN,NaN,NaN
4631,87585,2002-04-15,NaN,부에노스에이레스,NaN,-34.5833,-58.4833,NaN,NaN,NaN,NaN,NaN
4632,93110,2002-04-15,NaN,오클랜드,NaN,-37.0000,174.8000,7.00,NaN,NaN,NaN,NaN
4633,94578,2002-04-15,NaN,브리즈베인,NaN,-27.3833,153.1333,4.00,NaN,NaN,NaN,NaN
4634,94610,2002-04-15,NaN,퍼드,NaN,-31.9333,115.9667,20.00,NaN,NaN,NaN,NaN
4635,94672,2002-04-15,NaN,애들레이드,NaN,-34.9500,138.5333,6.00,NaN,NaN,NaN,NaN
4636,94767,2002-04-15,NaN,시드니,NaN,-33.9333,151.1667,6.00,NaN,NaN,NaN,NaN
4637,94866,2002-04-15,NaN,멜보른,NaN,-37.6667,144.8500,132.00,NaN,NaN,NaN,NaN
4638,94926,2002-04-15,NaN,캔버라,NaN,-35.3000,149.2000,576.00,NaN,NaN,NaN,NaN
4639,96749,2002-04-15,NaN,쟈카르타,NaN,-6.1167,106.6500,NaN,NaN,NaN,NaN,NaN
4640,98425,2002-04-15,NaN,마닐라,NaN,14.5833,120.9833,NaN,NaN,NaN,NaN,NaN

In [5]:
# 종관기상관측 번호만 가져오기
stnIds_list = sorted(list(set(stn['지점'])))
stnIds_list

[3,
 5,
 8,
 14,
 16,
 20,
 22,
 25,
 28,
 31,
 35,
 37,
 39,
 41,
 46,
 50,
 52,
 55,
 58,
 60,
 61,
 65,
 67,
 68,
 69,
 70,
 75,
 90,
 92,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 101,
 102,
 104,
 105,
 106,
 108,
 110,
 112,
 113,
 114,
 115,
 116,
 119,
 121,
 127,
 129,
 130,
 131,
 132,
 133,
 135,
 136,
 137,
 138,
 140,
 143,
 144,
 146,
 151,
 152,
 155,
 156,
 159,
 160,
 162,
 163,
 164,
 165,
 167,
 168,
 169,
 170,
 172,
 174,
 175,
 176,
 177,
 182,
 184,
 185,
 187,
 188,
 189,
 192,
 201,
 202,
 203,
 211,
 212,
 214,
 216,
 217,
 221,
 226,
 229,
 232,
 235,
 236,
 238,
 243,
 244,
 245,
 247,
 248,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 268,
 271,
 272,
 273,
 276,
 277,
 278,
 279,
 281,
 283,
 284,
 285,
 288,
 289,
 294,
 295,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 977,
 978,
 979,
 980,
 981,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1181,
 1182,
 1183,
 1185,
 1186,
 1187,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1250,
 1251,
 1252,
 1254,
 1256,
 1257,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1275,
 1276,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1336,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1343,
 1344,
 1345,
 1347,
 1348,
 1349,
 1350,
 1354,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1391,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1405,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1492,
 1493,
 1494,
 1495,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1502,
 ...]

In [6]:
url = 'http://data.kma.go.kr/apiData/getData'

apiKey = 'Huwx3d0MDSe1BHp9Z0ipkMaBFR9zjFWlTgk7R%2BcRmUEnfUGOmYasikzANiYKabCS'
type = 'json'
dataCd = 'ASOS'
dateCd = 'DAY'
startDt = '20140101'
endDt = '20181231'
stnIds = '108'
schListCnt = '10'
pageIndex = '1'

query = '?'+'apiKey='+apiKey+'&type='+type+'&dataCd='+dataCd+'&dateCd='+dateCd+'&startDt='+startDt+'&endDt='+endDt+'&stnIds='+stnIds+'&schListCnt='+schListCnt+'&pageIndex='+pageIndex

In [7]:
print(url+query)

http://data.kma.go.kr/apiData/getData?apiKey=Huwx3d0MDSe1BHp9Z0ipkMaBFR9zjFWlTgk7R%2BcRmUEnfUGOmYasikzANiYKabCS&type=json&dataCd=ASOS&dateCd=DAY&startDt=20140101&endDt=20181231&stnIds=108&schListCnt=10&pageIndex=1

In [8]:
# 예제
res = requests.get(url+query)
res.text

'[{"status":200},{"msg": "success"},{"stnIds": "108"},{"info":[{"AVG_M1_5_TE":9.2,"N9_9_RN":0,"MIN_RHM_HRMT":1459,"STN_ID":108,"MAX_INS_WS_WD":270,"MAX_PS_HRMT":2357,"MIN_RHM":29,"SS_DUR":9.6,"AVG_CM5_TE":0.3,"MAX_WS_WD":270,"AVG_TCA":2.1,"HR1_MAX_ICSR":1.13,"RNUM":1,"MAX_PS":1018.3,"AVG_M5_0_TE":17.3,"STN_NM":"서울","MAX_TA":7.9,"HR24_SUM_RWS":3218,"AVG_M3_0_TE":15.5,"AVG_CM10_TE":-0.2,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":14.8,"ISCS":"-{연무}-0235. {황사}0230-{황사}{강도0}0300-{황사}{강도0}0600-0620. {눈}0933-0935. {연무}1810-{연무}{강도0}2100-2310.","AVG_CM30_TE":1.5,"MAX_WS_HRMT":1256,"SUM_RN_DUR":0.03,"MAX_WD":270,"MIN_PS":1012.4,"TM":"2014-01-01","AVG_RHM":51.3,"MAX_INS_WS_HRMT":1304,"AVG_TS":0.8,"AVG_PV":4.2,"SUM_SS_HR":6.4,"AVG_PS":1014.2,"MAX_WS":7.8,"MAX_TA_HRMT":1535,"MIN_TG":-4.3,"SUM_SML_EV":1.8,"AVG_TD":-5.5,"AVG_TA":4,"AVG_CM20_TE":0.2,"MIN_TA":0.3,"MIN_PS_HRMT":1435,"AVG_M0_5_TE":2.6,"SUM_RN":0,"MIN_TA_HRMT":723,"AVG_LMAC":1.9,"SUM_GSR":6.17,"AVG_M1_0_TE":6.3,"AVG_PA":1003.6,"AVG_WS":3.7},{"AVG_M1_5_TE":9.1,"MAX_WD":290,"MIN_PS":1018.4,"TM":"2014-01-02","AVG_RHM":35.4,"STN_ID":108,"MIN_RHM_HRMT":1404,"MAX_INS_WS_WD":270,"AVG_TS":0,"MAX_INS_WS_HRMT":1327,"MAX_PS_HRMT":1031,"AVG_PV":2.3,"SUM_SS_HR":9,"MIN_RHM":17,"SS_DUR":9.6,"AVG_PS":1021.2,"MAX_WS":4,"AVG_CM5_TE":0.1,"MIN_TG":-5.4,"MAX_WS_WD":230,"MAX_TA_HRMT":1507,"SUM_SML_EV":2,"AVG_TCA":0.3,"HR1_MAX_ICSR":1.6,"AVG_TD":-12.9,"AVG_TA":1.5,"RNUM":2,"MAX_PS":1023.6,"AVG_CM20_TE":0.3,"MIN_PS_HRMT":1,"MIN_TA":-1.3,"AVG_M5_0_TE":17.3,"STN_NM":"서울","MAX_TA":6.2,"HR24_SUM_RWS":1685,"AVG_M3_0_TE":15.4,"AVG_CM10_TE":-0.2,"AVG_M0_5_TE":2.6,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":6,"AVG_LMAC":0,"MIN_TA_HRMT":724,"AVG_CM30_TE":1.6,"AVG_M1_0_TE":6.2,"SUM_GSR":9.18,"MAX_WS_HRMT":1124,"AVG_PA":1010.4,"AVG_WS":2},{"AVG_M1_5_TE":8.9,"MIN_RHM_HRMT":1311,"STN_ID":108,"MAX_INS_WS_WD":320,"MAX_PS_HRMT":52,"MIN_RHM":32,"SS_DUR":9.7,"AVG_CM5_TE":0.2,"MAX_WS_WD":320,"AVG_TCA":4.6,"HR1_MAX_ICSR":1.22,"MAX_PS":1020.9,"RNUM":3,"AVG_M5_0_TE":17.2,"MAX_TA":7.3,"STN_NM":"서울","HR24_SUM_RWS":2148,"AVG_M3_0_TE":15.3,"AVG_CM10_TE":-0.1,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":7.8,"ISCS":"{연무}1830-{연무}{강도0}2100-{연무}{강도0}2400-","AVG_CM30_TE":1.7,"MAX_WS_HRMT":2136,"MIN_PS":1014.8,"MAX_WD":50,"TM":"2014-01-03","AVG_RHM":54.4,"MAX_INS_WS_HRMT":2053,"AVG_TS":0.1,"AVG_PV":4,"SUM_SS_HR":2.7,"AVG_PS":1017.6,"MAX_WS":5.4,"MAX_TA_HRMT":1338,"MIN_TG":-5.1,"SUM_SML_EV":1.4,"AVG_TD":-6.2,"AVG_TA":2.3,"AVG_CM20_TE":0.5,"MIN_TA":-1.1,"MIN_PS_HRMT":1433,"AVG_M0_5_TE":2.6,"MIN_TA_HRMT":635,"AVG_LMAC":2,"SUM_GSR":4.69,"AVG_M1_0_TE":6.1,"AVG_PA":1006.9,"AVG_WS":2.5},{"AVG_M1_5_TE":8.8,"MIN_RHM_HRMT":1416,"STN_ID":108,"MAX_INS_WS_WD":270,"MAX_PS_HRMT":1032,"MIN_RHM":33,"SS_DUR":9.7,"AVG_CM5_TE":0,"MAX_WS_WD":290,"AVG_TCA":0.9,"HR1_MAX_ICSR":1.46,"MAX_PS":1021.2,"RNUM":4,"AVG_M5_0_TE":17.2,"MAX_TA":5.6,"STN_NM":"서울","HR24_SUM_RWS":2087,"AVG_M3_0_TE":15.3,"AVG_CM10_TE":0,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":7.6,"ISCS":"-{연무}-{연무}{강도0}0300-0315.","AVG_CM30_TE":1.7,"MAX_WS_HRMT":1749,"MIN_PS":1017.9,"MAX_WD":270,"TM":"2014-01-04","AVG_RHM":47.1,"MAX_INS_WS_HRMT":1748,"AVG_TS":-0.2,"AVG_PV":2.8,"SUM_SS_HR":8.7,"AVG_PS":1019.7,"MAX_WS":4.7,"MAX_TA_HRMT":1344,"MIN_TG":-6.4,"SUM_SML_EV":1.9,"AVG_TD":-10.3,"AVG_TA":-0.1,"AVG_CM20_TE":0.6,"MIN_TA":-3.7,"MIN_PS_HRMT":1404,"AVG_M0_5_TE":2.6,"MIN_TA_HRMT":722,"AVG_LMAC":0.5,"SUM_GSR":8.14,"AVG_M1_0_TE":6,"AVG_PA":1008.8,"AVG_WS":2.4},{"AVG_M1_5_TE":8.7,"MAX_WD":270,"MIN_PS":1021,"TM":"2014-01-05","AVG_RHM":48.4,"STN_ID":108,"MIN_RHM_HRMT":1557,"MAX_INS_WS_WD":250,"AVG_TS":-0.7,"MAX_INS_WS_HRMT":1521,"MAX_PS_HRMT":2314,"AVG_PV":2.7,"SUM_SS_HR":8,"MIN_RHM":27,"SS_DUR":9.7,"AVG_PS":1024.1,"MAX_WS":4.4,"AVG_CM5_TE":-0.2,"MIN_TG":-7,"MAX_WS_WD":290,"MAX_TA_HRMT":1418,"SUM_SML_EV":1.7,"AVG_TCA":2.1,"HR1_MAX_ICSR":1.29,"AVG_TD":-10.7,"AVG_TA":-0.8,"RNUM":5,"MAX_PS":1027.1,"AVG_CM20_TE":0.6,"MIN_PS_HRMT":11,"MIN_TA":-4.3,"AVG_M5_0_TE":17.2,"STN_NM":"서울","MAX_TA":3.8,"HR24_SUM_RWS":1660,"AVG_M3_0_TE":15.2,"AVG_CM10_TE":-0.1,"AVG_M0_5_TE":2.6,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":6.9,"AVG_LMAC":1.9,"MIN_TA_HRMT":810,"AVG_CM30_TE":1.7,"AVG_M1_0_TE":6,"SUM_GSR":7.08,"MAX_WS_HRMT":1543,"AVG_PA":1013.1,"AVG_WS":1.9},{"AVG_M1_5_TE":8.6,"MIN_RHM_HRMT":1353,"STN_ID":108,"MAX_INS_WS_WD":270,"MAX_PS_HRMT":1006,"MIN_RHM":31,"SS_DUR":9.7,"AVG_CM5_TE":-0.3,"MAX_WS_WD":290,"AVG_TCA":3.1,"HR1_MAX_ICSR":1.43,"MAX_PS":1030.3,"RNUM":6,"AVG_M5_0_TE":17.2,"MAX_TA":6.4,"STN_NM":"서울","HR24_SUM_RWS":1364,"AVG_M3_0_TE":15.1,"AVG_CM10_TE":-0.2,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":5.3,"ISCS":"{연무}1720-{연무}{강도0}1800-{연무}{강도0}2100-{연무}{강도0}2400-","AVG_CM30_TE":1.8,"MAX_WS_HRMT":1718,"MIN_PS":1026.7,"MAX_WD":50,"TM":"2014-01-06","AVG_RHM":50.4,"MAX_INS_WS_HRMT":1712,"AVG_TS":-0.5,"AVG_PV":3.2,"SUM_SS_HR":8.1,"AVG_PS":1028.2,"MAX_WS":3.8,"MAX_TA_HRMT":1428,"MIN_TG":-8,"SUM_SML_EV":1.6,"AVG_TD":-8.6,"AVG_TA":0.8,"AVG_CM20_TE":0.6,"MIN_TA":-3.7,"MIN_PS_HRMT":108,"AVG_M0_5_TE":2.5,"MIN_TA_HRMT":707,"AVG_LMAC":3,"SUM_GSR":7.9,"AVG_M1_0_TE":5.9,"AVG_PA":1017.3,"AVG_WS":1.6},{"AVG_M1_5_TE":8.5,"N9_9_RN":0,"MIN_RHM_HRMT":1151,"STN_ID":108,"MAX_INS_WS_WD":50,"MAX_PS_HRMT":10,"MIN_RHM":43,"SS_DUR":9.7,"AVG_CM5_TE":0.2,"MAX_WS_WD":200,"AVG_TCA":8.5,"HR1_MAX_ICSR":0.56,"RNUM":7,"MAX_PS":1027.6,"AVG_M5_0_TE":17.1,"STN_NM":"서울","MAX_TA":5.5,"HR24_SUM_RWS":1443,"AVG_M3_0_TE":15,"AVG_CM10_TE":-0.1,"HR1_MAX_ICSR_HRMT":1000,"MAX_INS_WS":4.4,"ISCS":"-{연무}-{연무}{강도0}0300-{연무}{강도0}0600-{연무}{강도0}0900-{연무}{강도0}1200-{연무}{강도0}1500-{연무}{강도0}1800-{연무}{강도0}2100-{연무}{강도0}2400- {비}2340-{비}{강도0}2400-","AVG_CM30_TE":1.7,"MAX_WS_HRMT":1352,"SUM_RN_DUR":0.33,"MAX_WD":20,"MIN_PS":1023.6,"TM":"2014-01-07","AVG_RHM":56,"MAX_INS_WS_HRMT":1012,"AVG_TS":0.5,"AVG_PV":4.3,"SUM_SS_HR":0,"AVG_PS":1025.4,"MAX_WS":3,"MAX_TA_HRMT":1429,"MIN_TG":-1.6,"SUM_SML_EV":0.8,"AVG_TD":-4.9,"AVG_TA":3,"AVG_CM20_TE":0.6,"MIN_TA":0.3,"MIN_PS_HRMT":2359,"AVG_M0_5_TE":2.6,"SUM_RN":0,"MIN_TA_HRMT":702,"AVG_LMAC":6,"SUM_GSR":3.36,"AVG_M1_0_TE":5.8,"AVG_PA":1014.6,"AVG_WS":1.7},{"AVG_M1_5_TE":8.4,"MIN_RHM_HRMT":1627,"STN_ID":108,"MAX_INS_WS_WD":290,"MAX_PS_HRMT":2321,"MIN_RHM":31,"SS_DUR":9.7,"AVG_CM5_TE":0.6,"MAX_WS_WD":270,"AVG_TCA":7.4,"HR1_MAX_ICSR":1.09,"RNUM":8,"MAX_PS":1024.1,"AVG_M5_0_TE":17,"STN_NM":"서울","MAX_TA":4,"HR24_SUM_RWS":2864,"AVG_M3_0_TE":14.9,"AVG_CM10_TE":0.2,"HR1_MAX_ICSR_HRMT":1400,"MAX_INS_WS":11.3,"ISCS":"-{연무}-{연무}{강도1}0300-0555. {박무}0550-{박무}{강도1}0600-{박무}{강도2}0900-1055. {연무}1050-{연무}{강도1}1200-{연무}{강도0}1500-1520. -{비}-0125.","AVG_CM30_TE":1.9,"MAX_WS_HRMT":1712,"SUM_RN_DUR":1.42,"MAX_WD":290,"MIN_PS":1018.9,"TM":"2014-01-08","AVG_RHM":56.6,"MAX_INS_WS_HRMT":1931,"AVG_TS":1.3,"AVG_PV":3.9,"SUM_SS_HR":3.5,"AVG_PS":1021.8,"MAX_WS":6,"MAX_TA_HRMT":1,"MIN_TG":-7.1,"SUM_SML_EV":1.8,"AVG_TD":-7.8,"AVG_TA":0.5,"AVG_CM20_TE":0.8,"MIN_TA":-5.7,"MIN_PS_HRMT":1422,"AVG_M0_5_TE":2.6,"SUM_RN":0,"MIN_TA_HRMT":2352,"AVG_LMAC":3,"SUM_GSR":5.59,"AVG_M1_0_TE":5.8,"AVG_PA":1010.9,"AVG_WS":3.3},{"AVG_M1_5_TE":8.3,"MAX_WD":290,"MIN_PS":1023.9,"TM":"2014-01-09","AVG_RHM":26.3,"STN_ID":108,"MIN_RHM_HRMT":1459,"MAX_INS_WS_WD":290,"AVG_TS":-4,"MAX_INS_WS_HRMT":1643,"MAX_PS_HRMT":2300,"AVG_PV":0.9,"SUM_SS_HR":9.3,"MIN_RHM":13,"SS_DUR":9.7,"AVG_PS":1029.2,"MAX_WS":6.8,"AVG_CM5_TE":-1.7,"MIN_TG":-12,"MAX_WS_WD":290,"MAX_TA_HRMT":1527,"SUM_SML_EV":1.8,"AVG_TCA":0,"HR1_MAX_ICSR":1.73,"AVG_TD":-24.3,"AVG_TA":-7.8,"RNUM":9,"MAX_PS":1031.6,"AVG_CM20_TE":0.6,"MIN_PS_HRMT":1,"MIN_TA":-10.4,"AVG_M5_0_TE":17.1,"STN_NM":"서울","MAX_TA":-4.3,"HR24_SUM_RWS":3083,"AVG_M3_0_TE":14.8,"AVG_CM10_TE":-0.4,"AVG_M0_5_TE":2.5,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":11.1,"AVG_LMAC":0,"MIN_TA_HRMT":732,"AVG_CM30_TE":1.9,"AVG_M1_0_TE":5.7,"SUM_GSR":10.06,"MAX_WS_HRMT":1625,"AVG_PA":1017.9,"AVG_WS":3.6},{"AVG_M1_5_TE":8.3,"N9_9_RN":0,"MIN_RHM_HRMT":107,"STN_ID":108,"MAX_INS_WS_WD":270,"MAX_PS_HRMT":1002,"MIN_RHM":30,"SS_DUR":9.8,"AVG_CM5_TE":-2,"MAX_WS_WD":270,"AVG_TCA":3.1,"HR1_MAX_ICSR":1.48,"RNUM":10,"MAX_PS":1033.4,"AVG_M5_0_TE":17,"STN_NM":"서울","MAX_TA":-0.9,"HR24_SUM_RWS":1696,"AVG_M3_0_TE":14.8,"AVG_CM10_TE":-1.1,"HR1_MAX_ICSR_HRMT":1200,"MAX_INS_WS":7.2,"ISCS":"{소낙눈}0915-0945. {소낙눈}1440-{소낙눈}{강도0}1500-1536.","AVG_CM30_TE":1.6,"MAX_WS_HRMT":1515,"SUM_RN_DUR":1.43,"MAX_WD":270,"MIN_PS":1030.5,"TM":"2014-01-10","AVG_RHM":48.6,"MAX_INS_WS_HRMT":1514,"AVG_TS":-3.1,"AVG_PV":2.2,"SUM_SS_HR":4.4,"AVG_PS":1031.7,"MAX_WS":4.2,"MAX_TA_HRMT":1307,"MIN_TG":-12.1,"SUM_SML_EV":1.3,"AVG_TD":-14.2,"AVG_TA":-4.7,"AVG_CM20_TE":0.1,"MIN_TA":-9.3,"MIN_PS_HRMT":1538,"AVG_M0_5_TE":2.4,"SUM_RN":0,"MIN_TA_HRMT":312,"AVG_LMAC":3.1,"SUM_GSR":6.91,"AVG_M1_0_TE":5.7,"AVG_PA":1020.6,"AVG_WS":2}]}]'

In [ ]:
# 관측소리스트로 반복문(전체데이터)
stnlist = stnIds_list
string = ''
for stn in stnlist:
    query = '?'+'apiKey='+apiKey+'&type='+type+'&dataCd='+dataCd+'&dateCd='+dateCd+'&startDt='+startDt+'&endDt='+endDt+'&stnIds='+str(stn)+'&schListCnt='+schListCnt+'&pageIndex='+pageIndex
    res = requests.get(url+query)
    string = string + res.text
gisang_raw = string

In [48]:
# json파일 저장
gisang = json.loads(gisang_raw)
with open('gisang.json', 'w', encoding="utf-8") as make_file:
    json.dump(gisang, make_file, ensure_ascii=False, indent="\t")

In [ ]:
# json파일 열기
with open('gisang.json',encoding='UTF-8') as data_file:
    data = json.load(data_file)

In [7]:
# 파싱
for i in range (0,len(data)):
    tm = data["info"][i]["tm"]
    stn_id = data["info"][i]["stn_id"]
    rnum = data["info"][i]["rnum"]
    avg_m1_5_te = data["info"][i]["avg_m1_5_te"]
    n9_9_rn = data["info"][i]["n9_9_rn"]
    min_ps = data["info"][i]["min_ps"]
    avg_rhm = data["info"][i]["avg_rhm"]
    min_rhm_hrmt = data["info"][i]["min_rhm_hrmt"]
    max_ins_ws_wd = data["info"][i]["max_ins_ws_wd"]
    avg_ts = data["info"][i]["avg_ts"]
    max_ins_ws_hrmt = data["info"][i]["max_ins_ws_hrmt"]
    dd_mes_hrmt = data["info"][i]["dd_mes_hrmt"]
    max_ps_hrmt = data["info"][i]["max_ps_hrmt"]
    avg_pv = data["info"][i]["avg_pv"]
    min_rhm = data["info"][i]["min_rhm"]
    sum_ss_hr = data["info"][i]["sum_ss_hr"]
    ss_dur = data["info"][i]["ss_dur"]
    avg_ps = data["info"][i]["avg_ps"]
    max_ws = data["info"][i]["max_ws"]
    avg_cm5_te = data["info"][i]["avg_cm5_te"]
    min_tg = data["info"][i]["min_tg"]
    max_ws_wd = data["info"][i]["max_ws_wd"]
    sum_sml_ev = data["info"][i]["sum_sml_ev"]
    avg_tca = data["info"][i]["avg_tca"]
    hr1_max_icsr = data["info"][i]["hr1_max_icsr"]
    avg_td = data["info"][i]["avg_td"]
    max_ps = data["info"][i]["max_ps"]
    avg_cm20_te = data["info"][i]["avg_cm20_te"]
    dd_mes = data["info"][i]["dd_mes"]
    min_ta = data["info"][i]["min_ta"]
    min_ps_hrmt = data["info"][i]["min_ps_hrmt"]
    avg_m5_0_te = data["info"][i]["avg_m5_0_te"]
    max_ta = data["info"][i]["max_ta"]
    hr24_sum_rws = data["info"][i]["hr24_sum_rws"]
    avg_m3_0_te = data["info"][i]["avg_m3_0_te"]
    avg_cm10_te = data["info"][i]["avg_cm10_te"]
    avg_m0_5_te = data["info"][i]["avg_m0_5_te"]
    hr1_max_icsr_hrmt = data["info"][i]["hr1_max_icsr_hrmt"]
    max_ins_ws = data["info"][i]["max_ins_ws"]
    avg_tca = data["info"][i]["avg_tca"]
    avg_cm30_te = data["info"][i]["avg_cm30_te"]
    avg_m1_0_te = data["info"][i]["avg_m1_0_te"]
    sum_gsr = data["info"][i]["sum_gsr"]
    max_ws_hrmt = data["info"][i]["max_ws_hrmt"]
    avg_pa = data["info"][i]["avg_pa"]
    avg_ws = data["info"][i]["avg_ws"]
    iscs = data["info"][i]["iscs"]
    sum_fog_dur = data["info"][i]["sum_fog_dur"]
    sum_lrg_ev = data["info"][i]["sum_lrg_ev"]
    sum_dpth_fhsc = data["info"][i]["sum_dpth_fhsc"]
    dd_mefs = data["info"][i]["dd_mefs"]
    dd_mefs_hrmt = data["info"][i]["dd_mefs_hrmt"]
    sum_rn = data["info"][i]["sum_rn"]
    hr1_max_rn_hrmt = data["info"][i]["hr1_max_rn_hrmt"]
    hr1_max_rn = data["info"][i]["hr1_max_rn"]
    mi10_max_rn_hrmt = data["info"][i]["mi10_max_rn_hrmt"]
    mi10_max_rn = data["info"][i]["mi10_max_rn"]
    
    if (i==0):
        df = pd.DataFrame({'tm':[tm], 'stn_id' : [stn_id], 
                           'rnum' : [rnum],'avg_m1_5_te' : [avg_m1_5_te],
                          'n9_9_rn' : [n9_9_rn], 'min_ps' : [min_ps],
                          'avg_rhm' : [avg_rhm], 'min_rhm_hrmt' : [min_rhm_hrmt],
                          'max_ins_ws_wd' : [max_ins_ws_wd], 'avg_ts' : [avg_ts],
                          'max_ins_ws_hrmt' : [max_ins_ws_hrmt], 'dd_mes_hrmt' : [dd_mes_hrmt],
                          'max_ps_hrmt' : [max_ps_hrmt], 'avg_pv' : [avg_pv],
                          'min_rhm' : [min_rhm], 'sum_ss_hr' : [sum_ss_hr],
                          'ss_dur' : [ss_dur], 'avg_ps' : [avg_ps],
                          'max_ws' : [max_ws], 'avg_cm5_te' : [avg_cm5_te],
                          'min_tg' : [min_tg], 'max_ws_wd' : [max_ws_wd],
                          'sum_sml_ev' : [sum_sml_ev], 'avg_tca' : [avg_tca],
                          'hr1_max_icsr' : [hr1_max_icsr], 'avg_td' : [avg_td],
                          'max_ps' : [max_ps], 'avg_cm20_te' : [avg_cm20_te],
                          'dd_mes' : [dd_mes], 'min_ta' : [min_ta],
                          'min_ps_hrmt' : [min_ps_hrmt], 'avg_m5_0_te' : [avg_m5_0_te],
                          'max_ta' : [max_ta], 'hr24_sum_rws' : [hr24_sum_rws],
                          'avg_m3_0_te' : [avg_m3_0_te], 'avg_cm10_te' : [avg_cm10_te],
                          'avg_m0_5_te' : [avg_m0_5_te], 'hr1_max_icsr_hrmt' : [hr1_max_icsr_hrmt],
                          'max_ins_ws' : [max_ins_ws], 'avg_tca' : [avg_tca],
                          'avg_cm30_te' : [avg_cm30_te], 'avg_m1_0_te' : [avg_m1_0_te],
                          'sum_gsr' : [sum_gsr], 'max_ws_hrmt' : [max_ws_hrmt],
                          'avg_pa' : [avg_pa], 'avg_ws' : [avg_ws],
                          'iscs' : [iscs], 'sum_fog_dur' : [sum_fog_dur],
                          'sum_lrg_ev' : [sum_lrg_ev], 'sum_dpth_fhsc' : [sum_dpth_fhsc],
                          'dd_mefs' : [dd_mefs], 'dd_mefs_hrmt' : [dd_mefs_hrmt],
                          'sum_rn' : [sum_rn], 'hr1_max_rn_hrmt' : [hr1_max_rn_hrmt],
                          'hr1_max_rn' : [hr1_max_rn], 'mi10_max_rn_hrmt' : [mi10_max_rn_hrmt],
                          'mi10_max_rn' : [mi10_max_rn]})
    else:
        df.loc[i] = [tm, stn_id, rnum, avg_m1_5_te, n9_9_rn, min_ps, avg_rhm, min_rhm_hrmt, max_ins_ws_wd, avg_ts, max_ins_ws_hrmt, dd_mes_hrmt, max_ps_hrmt, avg_pv, min_rhm, sum_ss_hr, ss_dur, avg_ps, max_ws, avg_cm5_te, min_tg, max_ws_wd, sum_sml_ev, avg_tca, hr1_max_icsr, avg_td, max_ps, avg_cm20_te, dd_mes, min_ta, min_ps_hrmt, avg_m5_0_te, max_ta, hr24_sum_rws, avg_m3_0_te, avg_cm10_te, avg_m0_5_te, hr1_max_icsr_hrmt, max_ins_ws, avg_tca, avg_cm30_te, avg_m1_0_te, sum_gsr, max_ws_hrmt, avg_pa, avg_ws, iscs, sum_fog_dur, sum_lrg_ev, sum_dpth_fhsc, dd_mefs, dd_mefs_hrmt, sum_rn, hr1_max_rn_hrmt, hr1_max_rn, mi10_max_rn_hrmt, mi10_max_rn]

NameError: name 'data' is not defined

In [ ]:
df.to_csv("수도시설.csv", encoding = 'ms949')